language: python
env:
  - TESTENV=py27
  - TESTENV=py33
  - TESTENV=py34
python:
    - "3.4"
addons:
  apt_packages:
    - pandoc
before_install:
 - sudo apt-get update -qq
 - sudo locale-gen fr_FR.UTF-8 tr_TR.UTF-8
install:
    - pip install python-coveralls
    - pip install -U virtualenv py
    - pip install -e . -r dev_requirements.txt tox
script:
  - tox
  - py.test --cov=pelican --cov-report=term-missing tests
after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls
notifications:
    irc:
        channels:
            - "irc.freenode.org#pelican"
        on_success: change
